services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentrifugo_web
    volumes:
      - ./sentrifugo:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: sentrifugo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sentrifugo
      MYSQL_USER: sentrifugo_user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: